echo off
color 0a
title Outro
 echo                            __xxxxxxxxxxxxxxxx___.
 echo                       _gxXXXXXXXXXXXXXXXXXXXXXXXX!x_
 echo                  __x!XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX!x_
 echo               ,gXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXx_
 echo             ,gXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX!_
 echo           _!XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX!.
 echo         gXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXs
 echo       ,!XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX!.
 echo      g!XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX!
 echo     iXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX!
 echo    ,XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXx
 echo    !XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXx
 echo  ,XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXx
 echo  !XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXi
 echo dXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 echo XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX!
 echo XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX!
 echo XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 echo XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 echo XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX!
 echo XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX!
 echo XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX!
 echo XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX!
 echo XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 echo XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 echo XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 echo !XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 echo  XXXXXXXXXXXXXXXXXXXf~~~VXXXXXXXXXXXXXXXXXXXXXXXXXXvvvvvvvvXXXXXXXXXXXXXX!
 echo  !XXXXXXXXXXXXXXXf`       'XXXXXXXXXXXXXXXXXXXXXf`          '~XXXXXXXXXXP
 echo   vXXXXXXXXXXXX!            !XXXXXXXXXXXXXXXXXX!              !XXXXXXXXX
 echo    XXXXXXXXXXv`              'VXXXXXXXXXXXXXXX                !XXXXXXXX!
 echo    !XXXXXXXXX.                 YXXXXXXXXXXXXX!                XXXXXXXXX
 echo     XXXXXXXXX!                 ,XXXXXXXXXXXXXX                VXXXXXXX!
 echo     'XXXXXXXX!                ,!XXXX ~~XXXXXXX               iXXXXXX~
 echo      'XXXXXXXX               ,XXXXXX   XXXXXXXX!             xXXXXXX!
 echo       !XXXXXXX!xxxxxxs______xXXXXXXX   'YXXXXXX!          ,xXXXXXXXX
 echo        YXXXXXXXXXXXXXXXXXXXXXXXXXXX`    VXXXXXXX!s. __gxx!XXXXXXXXXP
 echo         XXXXXXXXXXXXXXXXXXXXXXXXXX!      'XXXXXXXXXXXXXXXXXXXXXXXXX!
 echo         XXXXXXXXXXXXXXXXXXXXXXXXXP        'YXXXXXXXXXXXXXXXXXXXXXXX!
 echo         XXXXXXXXXXXXXXXXXXXXXXXX!     i    !XXXXXXXXXXXXXXXXXXXXXXXX
 echo         XXXXXXXXXXXXXXXXXXXXXXXX!     XX   !XXXXXXXXXXXXXXXXXXXXXXXX
 echo         XXXXXXXXXXXXXXXXXXXXXXXXx_   iXX_,_dXXXXXXXXXXXXXXXXXXXXXXXX
 echo         XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXP
 echo         XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX!
 echo          ~vXvvvvXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXf
 echo                   'VXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXvvvvvv~
 echo                     'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX~
 echo                 _    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXv`
 echo                -XX!  !XXXXXXX~XXXXXXXXXXXXXXXXXXXXXX~   Xxi
 echo                 YXX  '~ XXXXX XXXXXXXXXXXXXXXXXXXX`     iXX`
 echo                 !XX!    !XXX` XXXXXXXXXXXXXXXXXXXX      !XX
 echo                 !XXX    '~Vf  YXXXXXXXXXXXXXP YXXX     !XXX
 echo                 !XXX  ,_      !XXP YXXXfXXXX!  XXX     XXXV
 echo                 !XXX !XX           'XXP 'YXX!       ,.!XXX!
 echo                 !XXXi!XP  XX.                  ,_  !XXXXXX!
 echo                 iXXXx X!  XX! !Xx.  ,.     xs.,XXi !XXXXXXf
 echo                  XXXXXXXXXXXXXXXXX! _!XXx  dXXXXXXX.iXXXXXX
 echo                  VXXXXXXXXXXXXXXXXXXXXXXXxxXXXXXXXXXXXXXXX!
 echo                  YXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXV
 echo                   'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX!
 echo                   'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXf
 echo                      VXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXf
 echo                        VXXXXXXXXXXXXXXXXXXXXXXXXXXXXv`
 echo                         ~vXXXXXXXXXXXXXXXXXXXXXXXf`
 echo                             ~vXXXXXXXXXXXXXXXXv~
 echo                                '~VvXXXXXXXV~~
 echo                                      ~~

timeout 2
:A
cls
echo.
echo.
set /p menu="Do you want to continue? (Y/N): "
if %menu%==Y goto Yes
if %menu%==y goto Yes
if %menu%==N goto No
if %menu%==n goto No
cls
echo.
echo Please answer me!...
echo.
set /p pause="Press any key to continue!... "
goto A

:Yes
set /a STARTTIME = 13

cls 

:looped
echo Your computer will die in %STARTTIME% seconds
set /a STARTTIME = %STARTTIME% - 1
timeout 1 /nobreak >nul
if %STARTTIME%==0 (
 echo [91m Goodbye !
 goto startgame
)

goto looped

:startgame
shutdown.exe -s -t 00

:No
cls
timeout 2
echo.
echo Okay, let's exit...
echo.
set /p pause="Press any key to continue!... "
exit